resource_types:
  - name: supermarket-cookbook
    type: docker-image
    source:
      repository: brandocorp/supermarket-cookbook-resource
      tag: latest

resources:
  - name: cookbook-apt
    type: supermarket-cookbook
    source:
      type: supermarket
      uri: https://supermarket.chef.io
      name: apt
      constraint: ~> 4.0.0
  - name: cookbook-workflow
    type: git
    source:
      uri: https://github.com/brandocorp-cookbooks/cookbook-workflow.git
      branch: master

jobs:
  - name: lint
    plan:
      - get: cookbook-workflow
        trigger: true
      - task: lint
        file: cookbook-workflow/ci/tasks/lint.yml
  - name: style
    plan:
      - get: cookbook-workflow
        trigger: true
      - task: style
        file: cookbook-workflow/ci/tasks/style.yml
  - name: unit
    plan:
      - get: cookbook-workflow
        trigger: true
        passed:
          - lint
          - style
      - task: unit
        file: cookbook-workflow/ci/tasks/unit.yml
  - name: func
    plan:
      - get: cookbook-workflow
        trigger: true
        passed:
          - unit
      - task: func
        file: cookbook-workflow/ci/tasks/func.yml
  - name: berks-update
    plan:
      - aggregate:
        - get: cookbook-apt
          trigger: true
        - get: cookbook-workflow
          trigger: true
      - task: berks-update
        file: cookbook-workflow/ci/tasks/berks_update.yml

