name 'cookbook-workflow'
maintainer 'Brandon Raabe'
maintainer_email 'brandocorp@gmail.com'
license 'Apache 2.0'
description 'A cookbook for testing cookbook-workflow'
long_description 'A cookbook for testing cookbook-workflow'
version '0.1.0'
