platform: linux

image_resource:
  type: docker-image
  source:
    repository: brandocorp/chefdk
    tag: latest

inputs:
  - name: cookbook-workflow

run:
  path: cookbook-workflow/ci/scripts/style.sh
